import {
  Code2, Globe, Smartphone, Bot,
  LayoutDashboard, Cpu, MessageSquare, Landmark,
} from "lucide-react";

export const serviceGroups = [
  {
    label: "FINTECH & PAYMENT SOLUTIONS",
    items: [
      {
        name: "API Solutions",
        description: "AEPS, DMT, BBPS & more",
        fullName: "Fintech API Solutions",
        tooltipItems: [
          { term: "AEPS API", desc: "Aadhaar Enabled Payment System for cash withdrawal and banking transactions." },
          { term: "DMT API", desc: "Domestic Money Transfer — instant bank-to-bank transfers." },
          { term: "BBPS API", desc: "Bharat Bill Payment System for utility bill payments." },
          { term: "Recharge API", desc: "Mobile and DTH recharge integration." },
          { term: "Aadhaar Pay API", desc: "Biometric-based merchant payments using Aadhaar." },
          { term: "Account Verification API", desc: "Real-time bank account validation." },
          { term: "PAN Verification API", desc: "Instant PAN card verification." },
          { term: "UPI Collection API", desc: "Collect payments via UPI at scale." },
          { term: "Payment Gateway API", desc: "Accept online payments across channels." },
          { term: "KYC & eKYC API", desc: "Digital identity verification and onboarding." },
        ],
        href: "/services/api-solutions",
        icon: Code2,
      },
      {
        name: "White Label Solutions",
        description: "AEPS, recharge & B2B portals",
        fullName: "White Label Fintech Platforms",
        tooltipItems: [
          { term: "AEPS White Label Platform", desc: "Launch your own branded AEPS service." },
          { term: "Recharge White Label Software", desc: "Branded mobile and DTH recharge platform." },
          { term: "Fintech White Label Platform", desc: "Full-suite branded fintech app for your business." },
          { term: "BBPS White Label Portal", desc: "Branded bill payment portal." },
          { term: "B2B Recharge Portal", desc: "Distributor-facing recharge management portal." },
          { term: "Distributor & Retailer Portal", desc: "Hierarchical portal for managing your distribution network." },
        ],
        href: "/services/white-label-solutions",
        icon: LayoutDashboard,
      },
      {
        name: "Lending & Banking",
        description: "Loan management & NBFC software",
        fullName: "Lending & Banking Software",
        tooltipItems: [
          { term: "Loan Management Software", desc: "End-to-end loan lifecycle management." },
          { term: "Digital Lending Platform", desc: "Fully digital loan application and disbursal." },
          { term: "NBFC Software Solution", desc: "Core software for non-banking financial companies." },
          { term: "Loan Origination System (LOS)", desc: "Streamlined loan application and underwriting." },
          { term: "Collection Management System", desc: "Track and manage loan repayments and recovery." },
          { term: "Microfinance Software", desc: "Software tailored for microfinance institutions." },
        ],
        href: "/services/lending-banking",
        icon: Landmark,
      },
    ],
  },
  {
    label: "BUSINESS SOFTWARE",
    items: [
      {
        name: "Enterprise Solutions",
        description: "CRM, ERP, HRMS & payroll",
        fullName: "Enterprise Software Solutions",
        tooltipItems: [
          { term: "CRM Software", desc: "Manage customer relationships and sales pipelines." },
          { term: "ERP Software", desc: "Unified operations, inventory, and finance management." },
          { term: "HRMS Software", desc: "Human resource management system." },
          { term: "Payroll Management System", desc: "Automated salary processing and compliance." },
          { term: "Attendance Management System", desc: "Track employee attendance and shifts." },
          { term: "Employee Tracking Software", desc: "Monitor productivity and work hours." },
          { term: "Field Force Tracking Software", desc: "GPS-based tracking for field employees." },
          { term: "Visitor Management System", desc: "Digital check-in and visitor logging." },
        ],
        href: "/services/enterprise-solutions",
        icon: LayoutDashboard,
      },
      {
        name: "Customer Management",
        description: "Lead, sales & support CRMs",
        fullName: "Customer Management Software",
        tooltipItems: [
          { term: "Lead Management CRM", desc: "Capture, track, and convert leads." },
          { term: "Sales Automation CRM", desc: "Automate sales workflows and follow-ups." },
          { term: "Customer Support CRM", desc: "Manage customer queries and support history." },
          { term: "Ticketing & Helpdesk Software", desc: "Organize and resolve support tickets." },
          { term: "Call Center Management Software", desc: "Manage inbound/outbound call operations." },
        ],
        href: "/services/customer-management",
        icon: MessageSquare,
      },
    ],
  },
  {
    label: "E-COMMERCE & MARKETPLACE",
    items: [
      {
        name: "Commerce Solutions",
        description: "Marketplaces, D2C & delivery",
        fullName: "E-commerce & Marketplace Platforms",
        tooltipItems: [
          { term: "Ecommerce Website Development", desc: "Custom online store development." },
          { term: "Multi Vendor Marketplace", desc: "Platform supporting multiple independent sellers." },
          { term: "B2B Ecommerce Portal", desc: "Business-to-business online ordering platform." },
          { term: "D2C Ecommerce Store", desc: "Direct-to-consumer storefront." },
          { term: "Grocery Delivery Platform", desc: "On-demand grocery ordering and delivery." },
          { term: "Pharmacy Ecommerce Solution", desc: "Online pharmacy ordering platform." },
          { term: "Hyperlocal Delivery Platform", desc: "Local, fast-turnaround delivery system." },
        ],
        href: "/services/commerce-solutions",
        icon: Globe,
      },
      {
        name: "Retail Solutions",
        description: "POS, inventory & warehouse",
        fullName: "Retail Management Software",
        tooltipItems: [
          { term: "POS Billing Software", desc: "Point-of-sale billing for retail stores." },
          { term: "Inventory Management System", desc: "Track stock levels across locations." },
          { term: "Warehouse Management Software", desc: "Optimize warehouse operations and fulfillment." },
          { term: "Order Management System", desc: "Centralized order processing and tracking." },
        ],
        href: "/services/retail-solutions",
        icon: LayoutDashboard,
      },
    ],
  },
  {
    label: "TRAVEL & BOOKING SOLUTIONS",
    items: [
      {
        name: "Booking Platforms",
        description: "Flights, hotels, buses & trains",
        fullName: "Travel Booking Platforms",
        tooltipItems: [
          { term: "Flight Booking Portal", desc: "Online flight search and booking." },
          { term: "Bus Booking Software", desc: "Bus ticket reservation system." },
          { term: "Hotel Booking Engine", desc: "Hotel room search and reservation platform." },
          { term: "Train Booking Solution", desc: "Train ticket booking integration." },
          { term: "Holiday Package Portal", desc: "Curated holiday and tour package booking." },
          { term: "Travel Agent Portal", desc: "Portal for managing travel agent bookings." },
          { term: "B2B Travel Software", desc: "Business-to-business travel booking platform." },
          { term: "Travel CRM Solution", desc: "Manage travel leads and customer relationships." },
        ],
        href: "/services/booking-platforms",
        icon: Globe,
      },
    ],
  },
  {
    label: "TAX & COMPLIANCE SOLUTIONS",
    items: [
      {
        name: "Registration & Compliance",
        description: "GST, PAN, ITR & e-signatures",
        fullName: "Tax & Compliance Services",
        tooltipItems: [
          { term: "GST Registration Solution", desc: "Online GST registration assistance." },
          { term: "Tax Filing Software", desc: "Simplified tax return filing." },
          { term: "GST API Integration", desc: "Integrate GST compliance into your platform." },
          { term: "PAN Card Services", desc: "PAN application and verification services." },
          { term: "ITR Filing Platform", desc: "Income tax return filing platform." },
          { term: "Business Registration Solutions", desc: "Company and business registration support." },
          { term: "Digital Signature Services", desc: "Issue and manage digital signature certificates." },
        ],
        href: "/services/registration-compliance",
        icon: LayoutDashboard,
      },
    ],
  },
  {
    label: "COMMUNICATION (CPaaS)",
    items: [
      {
        name: "Messaging Solutions",
        description: "WhatsApp, SMS, RCS & chatbots",
        fullName: "CPaaS Messaging Solutions",
        tooltipItems: [
          { term: "WhatsApp Business API", desc: "Customer messaging and support over WhatsApp." },
          { term: "Bulk SMS Platform", desc: "Send bulk transactional and promotional SMS." },
          { term: "RCS Messaging", desc: "Rich, branded interactive messaging." },
          { term: "OTP SMS Services", desc: "Reliable OTP delivery for verification." },
          { term: "Email Marketing Platform", desc: "Automated email campaigns and analytics." },
          { term: "Omnichannel Communication", desc: "Unified messaging across channels." },
          { term: "Chatbot Development", desc: "Custom chatbot builds for support and sales." },
          { term: "Conversational AI", desc: "AI-driven conversational experiences." },
        ],
        href: "/services/messaging-solutions",
        icon: MessageSquare,
      },
    ],
  },
  {
    label: "DEVELOPMENT SERVICES",
    items: [
      {
        name: "Web & Mobile Development",
        description: "Websites, apps & SaaS products",
        fullName: "Web & Mobile Development",
        tooltipItems: [
          { term: "Website Development", desc: "Custom websites built for performance and scale." },
          { term: "Mobile App Development", desc: "Native and cross-platform mobile apps." },
          { term: "Flutter App Development", desc: "Cross-platform apps built with Flutter." },
          { term: "Android App Development", desc: "Native Android applications." },
          { term: "iOS App Development", desc: "Native iOS applications." },
          { term: "Custom Software Development", desc: "Bespoke software tailored to your workflow." },
          { term: "SaaS Product Development", desc: "End-to-end SaaS product builds." },
          { term: "Progressive Web Apps (PWA)", desc: "App-like experiences delivered through the browser." },
        ],
        href: "/services/web-mobile-development",
        icon: Smartphone,
      },
    ],
  },
  {
    label: "AI & EMERGING TECHNOLOGY",
    items: [
      {
        name: "AI Solutions",
        description: "Chatbots, voice AI & automation",
        fullName: "AI Solutions",
        tooltipItems: [
          { term: "AI Chatbot Development", desc: "Custom AI-powered chatbots." },
          { term: "Voice AI Solutions", desc: "Voice assistants and call automation." },
          { term: "Workflow Automation", desc: "Automate repetitive business processes." },
          { term: "Generative AI Integration", desc: "Integrate generative AI into your product." },
          { term: "AI Customer Support", desc: "AI-driven customer support automation." },
        ],
        href: "/services/ai-solutions",
        icon: Bot,
      },
      {
        name: "Cloud & DevOps",
        description: "AWS, Azure, GCP & CI/CD",
        fullName: "Cloud & DevOps Services",
        tooltipItems: [
          { term: "AWS Solutions", desc: "Cloud infrastructure on Amazon Web Services." },
          { term: "Azure Solutions", desc: "Cloud infrastructure on Microsoft Azure." },
          { term: "Google Cloud Solutions", desc: "Cloud infrastructure on Google Cloud Platform." },
          { term: "DevOps Implementation", desc: "End-to-end DevOps practices and tooling." },
          { term: "CI/CD Automation", desc: "Automated build, test, and deployment pipelines." },
        ],
        href: "/services/cloud-devops",
        icon: Cpu,
      },
      {
        name: "Cyber Security",
        description: "VAPT, audits & cloud security",
        fullName: "Cyber Security Services",
        tooltipItems: [
          { term: "VAPT Services", desc: "Vulnerability Assessment and Penetration Testing." },
          { term: "Security Audits", desc: "Comprehensive security review and reporting." },
          { term: "Compliance Solutions", desc: "Meet regulatory and security compliance standards." },
          { term: "Cloud Security", desc: "Secure your cloud infrastructure and data." },
        ],
        href: "/services/cyber-security",
        icon: LayoutDashboard,
      },
    ],
  },
];

export const products = [
  { name: "EzeePay", description: "AEPS, Money Transfer, Utility & Recharge", href: "/products/ezeepay", logo: "/ezeepay-logo-jpeg.webp" },
  { name: "Zoki", description: "Fastag Solution & Car Care Services", href: "/products/zoki", logo: "/zoki-icon.webp" },
  { name: "Mobilocker", description: "Secure Device Protection & Insurance Services", href: "/products/mobilocker", logo: "/mobilocker-icon.webp" },
  { name: "Skylist", description: "Coming soon", href: null, logo: "/skylist-logo.webp" },
  { name: "Cashlo", description: "UPI Cashpoint Platform for Every Shopkeeper", href: "https://cashlo-final-fxmt.vercel.app/", logo: "/cashlo-icon.svg" },
  { name: "Adkea", description: "Coming soon", href: null, logo: "/adkea-logo.webp" },
  { name: "Creditlo", description: "Coming soon", href: null, logo: "/creditlo-logo.webp" },
];